# kubernetes/namespaces/web-tier,cache-tier/kustomization.yaml

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# ğŸ‘‡ ì—¬ê¸°ì— secrets, configs í´ë” ê²½ë¡œë¥¼ ì¶”ê°€í•´ì•¼ í•©ë‹ˆë‹¤.
resources:
- ../web-tier/02-secrets  # Secret ë¦¬ì†ŒìŠ¤ë“¤ì´ ìˆëŠ” ê²½ë¡œ
- ../web-tier/03-configs  # ConfigMap ë¦¬ì†ŒìŠ¤ë“¤ì´ ìˆëŠ” ê²½ë¡œ
- ./04-applications     # Application Deploymentê°€ ìˆëŠ” ê²½ë¡œ
