# .../04-applications/kustomization.yaml (ìµœì¢… ìˆ˜ì •)

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- 01-backend-deployment.yaml
- 03-frontend-deployment.yaml  # í”„ë¡ íŠ¸ì—”ë“œ ë¦¬ì†ŒìŠ¤ ì¶”ê°€

images:
- name: backend-placeholder
  newName: 914215749228.dkr.ecr.ap-northeast-2.amazonaws.com/web-server-backend
  newTag: 922df8f
- name: frontend-placeholder   
  newName: 914215749228.dkr.ecr.ap-northeast-2.amazonaws.com/web-tier/frontend
  newTag: eb61fff

# ğŸ‘‡ ì•„ë˜ patches ë¸”ë¡ì„ ì¶”ê°€í•©ë‹ˆë‹¤.
patches:
- path: patch-backend-env.yaml
  target:
    kind: Deployment
    name: backend-deployment
